### ISSUE TITLE
white-space: nowrap

### ISSUE THREAD

**Issue by RSVT** [adobe-webplatform/balance-text#100]
Run into this a couple of times now where i have a two-part word that shouldn't be split. 
Anyway we could have it respect white-space:nowrap spans?

**Comment by redmunds** [comment]
That should be possible. Should also try to enforce &nbsp; while we're at it.

Thanks for filing bugs!

**Comment by mfehrenbach** [comment]
Seconded. We’ve been looking forward to implementing this on a big responsive project, but would love a way to keep certain words together. 

`nowrap` spans seem the most semantic (vs. `&nbsp;`, especially with more than two words), so we use those extensively to control our breaks—keeping people’s names together, date with the month, am/pm with the time, etc.

Is this difficult to implement?

**Comment by redmunds** [comment]
@mfehrenbach I haven't had time to play around with it. I'd start by creating some test cases. Then set a breakpoint in `isBreakOpportunity()`.

For `&nbsp;` case, maybe can detect that in `isWS()`

`white-space:nowrap` will not be easy to detect since that is forced on text to make text a single line so lengths, desired breaking positions, etc are easy to calculate. Maybe could set a custom attribute (similar to 'data-owner') on all tags with `white-space:nowrap` that could be detected in `isWS()` (similar to how it doesn't break inside '<'...'>'). That might be some tricky parsing.

**Comment by redmunds** [comment]
@RSVT @mfehrenbach I merged a fix for this into master. Please give it a test if you have time before I create Version 3.1. Thanks.

**Comment by mfehrenbach** [comment]
@redmunds This is great! Works really well in our testing here. 

Would you be able to publish version 3.1 to npm? We are hoping to roll this live in our project.

**Comment by mfehrenbach** [comment]
@redmunds Also, this is the project: https://www.moma.org

Let me know if you are in New York sometime, and we’ll get you some tickets to the Museum!

**Comment by redmunds** [comment]
@mfehrenbach Thanks for the feedback! Glad to hear I didn't missing ant glaring cases :) Thanks for ticket offers, but no plans to make it back East this year.

I am waiting for the last CDN to update [here](https://cdn.jsdelivr.net/balancetext/3.1.0/balancetext.min.js) before updating README pages and officially announcing 3.1 :

After that, I was going to notify @bfred-it to update npm (although npm users may not even use the CDNs).
