### ISSUE TITLE
Text should break on hyphens and dashes

### ISSUE THREAD

**Issue by IllyaMoskvin** [adobe-webplatform/balance-text#103]
I've noticed that the polyfill seems to avoid breaking hyphenated words, i.e. it treats each hyphenated word-pair as one word. I suspect this is because `isBreakOpportunity` ([L258](https://github.com/adobe-webplatform/balance-text/blob/master/balancetext.js#L258)) relies solely on spaces. Appending `|| txt[index-1] == '-'` solves the problem partially, but it doesn't account for n-dashes and m-dashes, and it causes persistent whitespace rifts to appear inside hyphenated words on repeated resize. I admit I haven't looked too deep into this issue.

In terms of use-case, I'm currently trying to make some centered blockquotes prettier automagically, and I'm running into issues with words like "nineteeth-century".

**Comment by redmunds** [comment]
@IllyaMoskvin Thanks for reporting bugs. I'm surprised that I never thought of this case.

I'd have to research whether to break on n-dash or m-dash, but breaking on dash would be a good start. Would you like to post a pull request?

**Comment by Rycochet** [comment]
Might be worth following the standards and looking for the `line-break` css property (which does include en/em-dash) -

https://drafts.csswg.org/css-text-3/#line-break-property

**Comment by bfred-it** [comment]
Don't forget `&shy;`

**Comment by redmunds** [comment]
@IllyaMoskvin @Rycochet @bfred-it I put up PR #104 to fix breaking on hyphens if anyone can give it a test.

The main issue I'd like feedback on is that code correctly breaks on soft-hyphens (`&shy;`), but since balance-text inserts `<br>` tag following `u00ad` char, then a hyphen does not appear in text (at end of line). Is that OK?

I suppose we could insert `<span data-owner="balance-text">-</span>` that could be removed with `<br>` tags in `removeTags()`.

**Comment by bfred-it** [comment]
>  a hyphen does not appear in text 
That's an issue

Reading text that is bro
ken like this is not prefer
rable

**Comment by redmunds** [comment]
> The span is a better solution, if we're going to target `&shy;`

@bfred-it Done

**Comment by redmunds** [comment]
@IllyaMoskvin @Rycochet @bfred-it Fix is in master. Please test if you have time before I create Version 3.1. Thanks.
