### ISSUE TITLE
All elements are being removed by removeTags function

### ISSUE THREAD

**Issue by bliker** [adobe-webplatform/balance-text#26]
Function is [here](https://github.com/adobe-webplatform/balance-text/blob/cad7f2bbb961791f6add31639b17a63a0a71a375/jquery.balancetext.js#L46-L57), from the way it is written it seems like it should only remove brs and spans. but it is setting text as html.

[demo](http://jsbin.com/arewis/2/edit) *Sometimes you need to refresh the page to load the resources properly*

**Comment by CupOfTea696** [comment]
What happened to this?

**Comment by redmunds** [comment]
@CupOfTea696 I'd love to get this in, but neither I or @rileyjshaw have had the time. Hopefully, within the next month.

If anyone else would like to try to implement the changes described here it would be great.

**Comment by CupOfTea696** [comment]
@redmunds oh that's a shame. Hopefully you will have the time in the future.

A temporary workaround I'm currently using is `$(':header:not(:has(*)), p:not(:has(*))).balanceText()'` in order to run it on as many elements as possible. It basically makes sure that your headings and paragraphs have no nested element before it runs `$.balanceText()`

**Comment by redmunds** [comment]
@bliker @Rycochet @cyxair @CupOfTea696 This has been fixed.

**Comment by CupOfTea696** [comment]
@redmunds thanks! any idea when the release is going to be?

**Comment by redmunds** [comment]
@CupOfTea696 It's available for download now, but I have not yet updated the CDN versions.
